# HERE WILL BE LOCATED ALL THE LANGUAGES OPTIONS AND CODES FOR TRANSCRIPTION

language_dict = {
    "Afrikaans": "afr",
    "Arabic": "ara",
    "Ashaninka": "cni",
    "Aymara": "aym",
    "Basque": "eus",
    "Bengali": "ben",
    "Catalan": "cat",
    "Chinese Mandarin": "cmn",
    "Dutch": "nld",
    "English": "eng",
    "French": "fra",
    "German": "deu",
    "Hindi": "hin",
    "Italian": "ita",
    "Japanese": "jpn",
    "Korean": "kor",
    "Persian": "fas",
    "Portuguese": "por",
    "Polish": "pol",
    "Punjabi (Eastern)": "pan",
    "Punjabi (Western)": "pnb",
    "Quechua Ayacucho": "quy",
    "Quechua Bolivia (Southern)": "quh",
    "Quechua Bolivia (Northern)": "qul",
    "Quechua Cajamarca": "qvc",
    "Quechua Cuzco": "quz",
    "Quechua San Martin": "qvs",
    "Romanian": "ron",
    "Russian": "rus",
    "Shipibo-Konibo": "shp",
    "Spanish": "spa",
    "Swahili": "swh",
    "Swedish": "swe",
    "Turkish": "tur",
    "Vietnamese": "vie",
}

language_list = list(language_dict.keys())
